
export enum FieldType {
  BOOLEAN = "boolean",
  COLLECTION = "collection",
  COLOR = "color",
  CURRENCY = "currency",
  DATE = "date",
  DURATION = "duration",
  EMAIL = "email",
  FILE = "file",
  LENGTH = "length",
  LIST = "list",
  NAME = "name",
  NUMBER = "number",
  OCCUPATION = "occupation",
  PERCENTAGE = "percentage",
  PHONE = "phone",
  PIPELINE = "pipeline",
  TEXT = "text",
  TYPE = "type",
  URL = "url",
}
