
export enum FieldType {
  AUDIO = "audio",
  BOOLEAN = "boolean",
  COLLECTION = "collection",
  COLOR = "color",
  DATE = "date",
  EMAIL = "email",
  FILE = "file",
  IMAGE = "image",
  LIST = "list",
  LOCATION = "location",
  MEASUREMENT = "measurement",
  NAME = "name",
  PERCENTAGE = "percentage",
  PERIOD = "period",
  PHONE = "phone",
  PIPELINE = "pipeline",
  PRICE = "price",
  QUANTITY = "quantity",
  RECURRENCE = "recurrence",
  TEXT = "text",
  TIME = "time",
  URL = "url",
  VIDEO = "video",
  VOLUME = "volume",
}
